namespace: "my_namespace"
name: "syncope"
version: "1.0.0"
readme: "README.md"
authors:
    - "Matteo Alessandroni"
dependencies:
license:
    - "MIT"
tags:
    - syncope
repository: "https://www.github.com/my_org/my_collection"
documentation: "http://my-docs.example.com"
homepage: "http://www.example.com"
issues: "https://www.github.com/my_org/my_collection/issues"
