namespace: "my_namespace"
name: "syncope"
version: "1.0.0"
readme: "README.md"
authors:
  - "Matteo Alessandroni"
dependencies:
license:
  - "MIT"
tags:
  - syncope
repository: "https://github.com/Tirasa/SyncopeAnsible"
documentation: ""
homepage: "https://github.com/Tirasa/SyncopeAnsible"
issues: "https://github.com/Tirasa/SyncopeAnsible/issues"
